"""
Export utilities for RAG system.

This module provides export functionality for:
- Markdown format
- PDF format (using reportlab)
"""

import datetime
from pathlib import Path
from typing import Any

from src.core.logging import LoggerMixin, get_logger

logger = get_logger(__name__)


def export_to_markdown(
    response: dict[str, Any],
    query: str = "",
    include_sources: bool = True,
    include_metadata: bool = True,
) -> str:
    """
    Export response to Markdown format.
    
    Args:
        response: Response dictionary with 'answer', 'sources', etc.
        query: Original query
        include_sources: Include source citations
        include_metadata: Include token usage and other metadata
        
    Returns:
        Formatted Markdown string
    """
    parts = []
    
    # Header
    parts.append("# Query Response")
    parts.append(f"\n**Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")
    
    if query:
        parts.append(f"\n**Query:** {query}\n")
    
    parts.append("---\n")
    
    # Answer
    parts.append("## Answer\n")
    parts.append(response.get("answer", "No answer available."))
    parts.append("\n")
    
    # Sources
    if include_sources and response.get("sources"):
        parts.append("---\n")
        parts.append("## Sources\n")
        for i, source in enumerate(response["sources"], 1):
            parts.append(f"{i}. `{source}`")
        parts.append("\n")
    
    # Source documents
    if include_sources and response.get("source_documents"):
        parts.append("---\n")
        parts.append("## Referenced Documents\n")
        for i, doc in enumerate(response["source_documents"][:5], 1):
            filename = doc.get("metadata", {}).get("filename", "Unknown")
            similarity = doc.get("similarity", doc.get("rerank_score", 0))
            parts.append(f"### Document {i}: {filename}")
            parts.append(f"*Relevance: {similarity:.3f}*\n")
            content = doc.get("document", "")[:500]
            parts.append(f"```\n{content}...\n```\n")
    
    # Metadata
    if include_metadata and response.get("token_usage"):
        usage = response["token_usage"]
        parts.append("---\n")
        parts.append("## Metadata\n")
        parts.append(f"- **Prompt Tokens:** {usage.get('total_prompt_tokens', 'N/A')}")
        parts.append(f"- **Completion Tokens:** {usage.get('total_completion_tokens', 'N/A')}")
        parts.append(f"- **Estimated Cost:** ${usage.get('total_cost', 0):.6f}")
        parts.append(f"- **Query Type:** {response.get('query_type', 'N/A')}")
        parts.append("\n")
    
    # Footer
    parts.append("---\n")
    parts.append("*Generated by RAG System*")
    
    return "\n".join(parts)


def export_to_pdf(
    response: dict[str, Any],
    output_path: str | Path,
    query: str = "",
    include_sources: bool = True,
) -> Path:
    """
    Export response to PDF format.
    
    Args:
        response: Response dictionary with 'answer', 'sources', etc.
        output_path: Path for output PDF file
        query: Original query
        include_sources: Include source citations
        
    Returns:
        Path to created PDF file
        
    Raises:
        ImportError: If reportlab is not installed
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError:
        raise ImportError(
            "PDF export requires reportlab. Install with: pip install reportlab"
        )
    
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Create PDF document
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
    )
    
    # Get styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=20,
        textColor=colors.darkblue,
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=10,
        textColor=colors.darkblue,
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        spaceAfter=12,
        leading=14,
    )
    
    # Build content
    story = []
    
    # Title
    story.append(Paragraph("Query Response Report", title_style))
    story.append(Spacer(1, 0.2 * inch))
    
    # Date and query
    date_str = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    story.append(Paragraph(f"<b>Date:</b> {date_str}", body_style))
    
    if query:
        story.append(Paragraph(f"<b>Query:</b> {query}", body_style))
    
    story.append(Spacer(1, 0.3 * inch))
    
    # Answer section
    story.append(Paragraph("Answer", heading_style))
    
    # Clean answer text for PDF
    answer = response.get("answer", "No answer available.")
    answer = answer.replace("<", "&lt;").replace(">", "&gt;")
    story.append(Paragraph(answer, body_style))
    
    story.append(Spacer(1, 0.3 * inch))
    
    # Sources section
    if include_sources and response.get("sources"):
        story.append(Paragraph("Sources", heading_style))
        for source in response["sources"]:
            story.append(Paragraph(f"• {source}", body_style))
        story.append(Spacer(1, 0.2 * inch))
    
    # Token usage table
    if response.get("token_usage"):
        usage = response["token_usage"]
        story.append(Paragraph("Usage Statistics", heading_style))
        
        table_data = [
            ["Metric", "Value"],
            ["Prompt Tokens", str(usage.get("total_prompt_tokens", "N/A"))],
            ["Completion Tokens", str(usage.get("total_completion_tokens", "N/A"))],
            ["Estimated Cost", f"${usage.get('total_cost', 0):.6f}"],
        ]
        
        table = Table(table_data, colWidths=[2 * inch, 2 * inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.darkblue),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ]))
        
        story.append(table)
    
    story.append(Spacer(1, 0.5 * inch))
    
    # Footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.grey,
        alignment=1,  # Center
    )
    story.append(Paragraph("Generated by RAG System", footer_style))
    
    # Build PDF
    doc.build(story)
    
    logger.info(f"PDF exported to: {output_path}")
    
    return output_path


class Exporter(LoggerMixin):
    """Exporter class for various formats."""
    
    def __init__(self, output_dir: str | Path = "./exports"):
        """
        Initialize exporter.
        
        Args:
            output_dir: Directory for exported files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.logger.info(f"Exporter initialized: {self.output_dir}")
    
    def export(
        self,
        response: dict[str, Any],
        format: str = "markdown",
        filename: str | None = None,
        query: str = "",
    ) -> Path:
        """
        Export response to specified format.
        
        Args:
            response: Response to export
            format: Export format (markdown, pdf)
            filename: Output filename (auto-generated if None)
            query: Original query
            
        Returns:
            Path to exported file
        """
        # Generate filename if not provided
        if not filename:
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"response_{timestamp}"
        
        if format.lower() in ["markdown", "md"]:
            content = export_to_markdown(response, query=query)
            output_path = self.output_dir / f"{filename}.md"
            output_path.write_text(content, encoding="utf-8")
            self.logger.info(f"Exported to Markdown: {output_path}")
            return output_path
            
        elif format.lower() == "pdf":
            output_path = self.output_dir / f"{filename}.pdf"
            return export_to_pdf(response, output_path, query=query)
        
        else:
            raise ValueError(f"Unsupported export format: {format}")


# Default exporter instance
default_exporter = Exporter()


__all__ = [
    "export_to_markdown",
    "export_to_pdf",
    "Exporter",
    "default_exporter",
]
